name: Actualizador SgoAhorro
on:
  schedule:
    - cron: '0 11 * * *' # Esto corre todos los días a las 8 AM hora Argentina
  workflow_dispatch: # Esto te permite correrlo a mano cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install selenium webdriver-manager httpx

      - name: Ejecutar Robot
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          MASONLINE_COOKIE: ${{ secrets.MASONLINE_COOKIE }} # <--- ESTA ES LA LÍNEA CLAVE
        run: python cazador.py
